(* main.ml -- Unikernel entry point (Unix backend).
   
   THIS IS WHERE THE FUNCTOR GETS INSTANTIATED.
   
   We take our abstract DNS_service and plug in the Unix implementations.
   In MirageOS, this file is auto-generated by the `mirage` tool.
   The tool reads your config, picks the right backends for your
   target platform, and generates this wiring code.
   
   We're doing it by hand to understand what's happening under the hood.
   
   KEY INSIGHT: Changing from Unix to a hypervisor backend would mean
   changing ONLY this file. The DNS service code stays identical. *)

(* Instantiate the functor with Unix backends *)
module Server = Dns_service.Make(Net_unix.Udp_unix)(Net_unix.Console_unix)

(* This is `main()`. On a real unikernel, there's no OS beneath us --
   Lwt_main.run IS the operating system's event loop. *)
let () =
  let port = match Sys.argv with
    | [| _; p |] -> int_of_string p
    | _ -> 5353
  in
  Lwt_main.run (Server.start ~port)
